name: Stack Action

on:
  pull_request:
    branches:
      - "**"

jobs:
  git-town:
    name: Display the branch stack
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: mattd-tg/stack-action@v1
        with:
          main-branch: "main"
          skip-single-stacks: true
